language: node_js
node_js:
- '7'
- '6'
- '0.12'
branches:
  only:
  - master
deploy:
  skip_cleanup: true
  provider: npm
  email: chadkillingsworth@gmail.com
  on:
    node: '6'
    branch: master
  api_key:
    secure: hveqvuKgh8GH7m+2hUjToPYOB/kdfIlcJQ7bLcWHxYWtuviMs4MAkZyAwmZuWBfIGftltvm+pbRmd8WVTZZWXpzoBrSq8xnRpqfRHa0IUJlUX8zar/m8oUXHU4NB5qFMI17zArkC9gTVtuK7EM3jnoVYAFyOv9+btUvMmAc15X70Qx/FSfP6GfFZ7X8ZTPkW5I1KYELjq1DIl4Ycg/ZxuF/AhC8r8pPKWhltY9rmwBzsl3bO+YEFSL7Kpb5D56wHYalPbEHGitu+ormSh+oSTll3d3LG32yX+x91Fyu3au2s5GvJc7Jb7tI1af02CrtlSeGCUZVbMIzVxaHXtZiBLpx6sa10u97Hhd0ysnVqJX+p7hCOwZI6Z77pS6m4VlXXR2HD7JNpLmGSHWVHtSONjrsw5uo/4x15vqfOI6ZaCTiv6wtnkqmCmc5kpmy+TYXJGb6AtoXSgDsH8DI4t+ptgsWWvrHMOhAECK/SfFrN106hd78mCzD7SRuAPTdk9toeXNxkuArVNGpzE4+gbotFEVWsPGhwxYWJz6detHUhoU4wJwXLPHXoXkmczDVw0GwLwetv6fSyjEYk270HFMDVw0oF0VKtbWLANkgA5KQwfyjfCFnJXJMUHTcoLUTIo56RfIyzGeumiS93Yk+Y7DTBD8qYwzTKIXCNVGnbM7JWyKY=
