language: node_js
node_js:
- '5.1'
- '0.12'
after_success:
 - git config user.name "Travis CI"
 - git config user.email "chadkillingsworth@gmail.com"
 - gulp release-if-changed
 - git push "https://${GH_TOKEN}@github.com/ChadKillingsworth/closure-compiler-npm.git" master
deploy:
  skip_cleanup: true
  provider: npm
  email: chadkillingsworth@gmail.com
  on:
    node: '5.1'
    branch: master
  api_key:
    secure: Tuuebi/+0YTMiDvij1DQh//wXb6pLi0pJgXw+GgawnKQjqSG55BjYtGK7XJ7KPSYXBghXq0gioFSFFWXH1lot9wyhFxtieHhVat6RLsbjq1jHVjLFmC+BuM7tuuuBniBU5ZGnmQPjrCsWYLDU7u9RDzWD5jmi1xM3ujzkghVBsxxEDo5mIveN4f3rt2Ph4NE7Sp8JTe7eKMV8EN5LFiS7lJpQeBYYLqEIx2iQCpdjVTVHkU56d+w81Emvi+F7tXEHgMFtGF1KfbBtp6L3jlCjA8sSdUN/oiJ/6xO+znwHFJYCBALCL+ooEuq5uK85WasJvJ4AOeFuFlWtIM7nMUJJbOweiF6ktKBPgELII4qn7ItTWkVeQkoOGGKSmlNZ1D4eKhjnj8XQZ7PDkLd2mEnEs3dimVCFrPYnb++BH7OjAKskQ+6CT4bLTBKXCf5slMYgfYVmYvF12tIxgo5reFyGlqO8K/VhqNFOw4lJHnB9fDtP8uvfZr8msYwo46xT5i34yXUxzyg4nSIOdZmCiheyrcXxDkrGoWbW+SDzWm1gozhYGcoAoiXADqEfdJEYVAfTz5bsbOykqiUbSzNCuWz4EclzW3VvJtG7ulc2weZYR6Fi0MvA4r1hIAp4UrKVLb+h6aJC92Nm+VCbJ4B+VbR71p2E9Y2C/fRLDaG5qGxgaQ=
env:
  global:
    GH_TOKEN:
      secure: lFRNFNKpiP/S14mnTrl3RzH/q9SYf/8GP7dgiH8wlAgnd1XnkZbKFG978VtJCNTOioNPLpwgOTib5I7DAJnBalWszjDAj1hXC3oUa1/EPRST2KDX/04187cj4C/HgbIm8Glrj0m/e0+G5vAKsd0C644JQ07wZQNaMuCPLrSZILjW8Z9Wwaa51zzUDmSsYpX7UHuIWZxTtmCULHAK34rHzXb/ltnYwzJdyT+yt6Ji4pD6X3dZIPU5Y3WwubiqC6O7NO9uYm5gNPPhrxYseYG0pH2t3I9UB4/5kZRG3ejvgbyfkmvy+3a38cXoB0+GoupcVZgRfWTR8rMj7z2FNjhmpUXEHxpK0vdgX72gAHma81OVJF1g1VRctkvEyMsr4IosifruzbJXAAEQ+n07ZGAgOF9QxzBfZYezlMVDF9vx3+WbHKsNSqc4583Jrivjn3SE+uBgffSzeMWeLtl/eVvZl93XYGio+WERSFuu3gniS/zkuVyRo3Ouiy/zEEb6WNdsm94/u2ToRTkPJ9VebOELu8sThYqMsWx7Ai/3CKPm8Kj+Hu6Zctmwibtt4gS+ttQKQZssrGx9/yspS5hU8GKphpFaNDwP9zjhQtJVhlydHOrS7dwy1hfKlx/t2Q6R/RaRax+3l+uYBSBPk2Vwe63i2cIhNUuOMDCEiyURQnZScU0=
